spring:
  application:
    name: gateway-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

management:
  endpoint:
    web:
      exposure:
        include: health, resilience4j
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/