spring:
  application:
    name: gateway-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  config:
    import: "configserver:"