spring:
  application:
    name: gateway-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  config:
    import: "configserver:http://localhost:8888"

management:
  endpoint:
    health:
      show-details: always